### ISSUE TITLE
ToDo Roundup

### ISSUE THREAD

**Issue by jtdroste** [ubnetdef/ie2#11]
- [x] Scheduler Manager
    - [x] Create Schedule
    - [x] Edit Schedule
    - [x] Delete Schedule
    - [x] Duplicate/Extend Schedule
- [ ] Site Manager
    - [x] Site config view/edit
    - [ ] Site env dump
- [x] User Manager
    - [x] Typical CRUD, add in group stuff
- [x] Inject Manager
    - [x] Typical CRUD
- [x] Log Manager
    - [x] ????
- [x] Team Panel
    - [x] CRUD
- [x] Bank UI
    - [x] CRUD

**Comment by jtdroste** [comment]
Closing - not going to do ENV dump due to creds.
